name: 'web_app'
version: 0.0.1
description: Web App de Mi Águila
#author: Juan Martínez <juan.mar@gmail.com>
#homepage: https://app.miaguila.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha+22
  google_maps:   "3.4.0"
  stream_transform: ^0.0.6
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  dart_jsonwebtoken: ^1.6.2


